# Base image
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# # Copy requirements and install
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# Copy API source code
COPY api/app/ ./app/

# Set environment variables (optionnel)
ENV PYTHONUNBUFFERED=1

# Launch API
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
