# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-pv
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   hostPath:
#     path: /data/minio
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: minio-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard  # important pour Docker Desktop
#   resources:
#     requests:
#       storage: 2Gi
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: minio
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: minio
#   template:
#     metadata:
#       labels:
#         app: minio
#     spec:
#       containers:
#         - name: minio
#           image: minio/minio:latest
#           args:
#             - server
#             - /data
#             - "--console-address"
#             - ":8900"
#           ports:
#             - containerPort: 9000
#             - containerPort: 8900
#           env:
#             - name: MINIO_ROOT_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: minio-secret
#                   key: MINIO_USER
#             - name: MINIO_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: minio-secret
#                   key: MINIO_PASS
#           volumeMounts:
#             - name: minio-data
#               mountPath: /data
#       volumes:
#         - name: minio-data
#           persistentVolumeClaim:
#             claimName: minio-pvc
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: minio
# spec:
#   type: NodePort
#   selector:
#     app: minio
#   ports:
#     - name: api
#       port: 9000
#       targetPort: 9000
#       nodePort: 30900  
#     - name: ui
#       port: 8900
#       targetPort: 8900
#       nodePort: 30890

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - "--console-address"
            - ":8900"
          ports:
            - containerPort: 9000
            - containerPort: 8900
          env:
            - name: MINIO_ROOT_USER
              value: minio  # ou remplace par la vraie valeur
            - name: MINIO_ROOT_PASSWORD
              value: miniopassword  # ou remplace par la vraie valeur
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          emptyDir: {}  #  pas de persistance
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30900  
    - name: ui
      port: 8900
      targetPort: 8900
      nodePort: 30890
