# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard  
#   resources:
#     requests:
#       storage: 2Gi

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgres-pv
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   hostPath:
#     path: /data/postgres

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#         - name: postgres
#           image: postgres:14-alpine
#           ports:
#             - containerPort: 5432
#           env:
#             - name: POSTGRES_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: postgres-secret
#                   key: POSTGRES_USER
#             - name: POSTGRES_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: postgres-secret
#                   key: POSTGRES_PASSWORD
#             - name: POSTGRES_DB
#               valueFrom:
#                 secretKeyRef:
#                   name: postgres-secret
#                   key: DB_NAME
#           volumeMounts:
#             - name: postgres-storage
#               mountPath: /var/lib/postgresql/data
#       volumes:
#         - name: postgres-storage
#           persistentVolumeClaim:
#             claimName: postgres-pvc

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres
# spec:
#   type: NodePort
#   selector:
#     app: postgres
#   ports:
#     - port: 5432
#       targetPort: 5432
#       nodePort: 30432


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_DB
              value: airflow_db
          volumeMounts:
            - name: tmp-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: tmp-data
          emptyDir: {}  # Pas de persistance

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
