# Base Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy frontend code
COPY frontend.py .

# Install dependencies
# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install --no-cache-dir streamlit requests pillow

# Expose Streamlit's default port
EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
