# Base image
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy API source code
COPY app/ ./

# Set environment variables (allowing to see logs in real-time)
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app
# Launch API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
