name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker_compose.yaml up -d
          docker-compose -f docker_compose.yaml ps

      - name: Wait for Airflow Init to complete
        run: |
          echo "Waiting for Airflow Init to complete..."
          for i in {1..10}; do
            if docker-compose -f docker_compose.yaml logs airflow-init | grep -q "Database successfully upgraded"; then
              echo "Airflow Init completed successfully!"
              break
            fi
            echo "Airflow Init not ready yet. Retrying in 10 seconds..."
            sleep 10
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest tests/

      - name: Debug Docker logs
        if: failure()
        run: |
          echo "Fetching logs for debugging..."
          docker-compose -f docker_compose.yaml logs

      - name: Stop services
        run: |
          docker-compose -f docker_compose.yaml down