name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker_compose.yaml up -d
          docker-compose -f docker_compose.yaml ps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Airflow to initialize
        run: |
          sleep 30  # Attendre que les services soient prêts

      - name: Initialize Airflow database
        run: |
          docker-compose -f docker_compose.yaml exec webserver airflow db init

      - name: Run Pytest
        run: |
          pytest tests/

      - name: Stop services
        run: |
          docker-compose -f docker_compose.yaml down